#!/bin/bash

# This script is a wrapper around the mmdc command that passes in the
# necessary --no-sandbox flag via a config file. This is required to run
# mmdc in an environment where it would otherwise be blocked by sandboxing.
#
# Usage:
#   ./render_mermaid.sh <input_file.md> [output_file.md]
#
# If output_file.md is not provided, it will be generated by appending
# "_with_diagrams" to the input file name.

set -euo pipefail

if [ "$#" -lt 1 ] || [ "$#" -gt 2 ]; then
    echo "Usage: $0 <input_file.md> [output_file.md]" >&2
    exit 1
fi

INPUT_FILE=$1
OUTPUT_FILE=${2:-${INPUT_FILE%.md}_with_diagrams.md}


if ! [ -f "node_modules/.bin/mmdc" ]; then
    echo "Error: mmdc not found. Please run 'npm install' first." >&2
    exit 1
fi

echo "Rendering diagrams from $INPUT_FILE to $OUTPUT_FILE..."
./node_modules/.bin/mmdc -p puppeteer-config.json -i "$INPUT_FILE" -o "$OUTPUT_FILE" > /dev/null

echo "Done."
